name: CICD
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t ptuan123987/reactjs-app:latest  .
      - name: Publish image to docker hub
        run: docker push ptuan123987/reactjs-app:latest 
        
  deploy: 
    needs: build
    runs-on: self-hosted    
    steps:
      - name: Pull image from docker hub
        run: sudo docker pull ptuan123987/reactjs-app:latest 
      - name: Delete Old Container
        run: sudo docker rm -f react-container
      - name: Run docker container
        run: sudo docker run -d -p 3000:80 --name react-container ptuan123987/reactjs-app:latest

   
